packages/web/src/containers/swap-container/SwapContainer.tsx
Added URL handling based on token selection and swap direction on the swap page.
=> [GSW-448] feat: Apply swap page query string

packages/web/src/containers/incentivize-pool-modal-container/IncentivizePoolModalContainer.tsx
When you run a function that generates an Incentive from the Stake package, 
time argument to UTC time to Unix time.
cc @r3v4s
=> feat: Change Incentive creation time to unix time

packages/web/src/containers/remove-position-modal-container/RemovePositionModalContainer.tsx, packages/web/src/repositories/position/position-repository-impl.ts
Change the quantity of Token Approve to the number of INT64 in the following PR change. https://github.com/gnoswap-labs/gnoswap-interface/pull/332
=> fix: Change approve token amount

packages/web/src/repositories/position/position-repository-impl.ts
- Add Approval token transaction messages when collect fee
=> feat: Add a approve token when collect fee

packages/web/src/hooks/swap/use-swap-handler.tsx
When token swap, calculate the price impact of the expected output.
=> fix: Calculate price impact

packages/web/src/common/clients/wallet-client/transaction-messages/common.ts, packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/repositories/pool/pool-repository-impl.ts
When sending a GNOT native token to a contract, change it to treat it as a space if it's 0ugnot.
=> fix: Fix GNOT send to contract for zero amount

packages/web/src/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/containers/pool-add-liquidity-container/PoolAddLiquidityContainer.tsx, packages/web/src/hooks/pool/use-select-pool.tsx, packages/web/src/react-query/pools/queries.ts, packages/web/src/utils/swap-utils.ts
When adding positions, modify the quantity calculation by price range.
=> fix: Fix incorrect Deposit Ratio calculation in Add Position

packages/web/src/components/token/token-chart/token-chart-graph/TokenChartGraph.spec.tsx, packages/web/src/components/token/token-chart/token-chart-graph/TokenChartGraph.styles.ts, packages/web/src/components/token/token-chart/token-chart-graph/TokenChartGraph.tsx
Improve the token price graph.
- Change the x-axis data to display correctly.
=> feat: Improve the token price graph.

packages/web/src/components/pool/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/components/pool/my-position-card/MyPositionCard.tsx, packages/web/src/constants/option.constant.ts
The `INTERNAL` Reward type is added.
=> feat: Migrate reward type

packages/web/src/common/values/data-constant.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.styles.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card/SwapCard.tsx, packages/web/src/hooks/swap/use-swap-handler.tsx, packages/web/src/hooks/swap/use-swap.tsx, packages/web/src/react-query/router/queries.ts, packages/web/src/repositories/swap/swap-router-repository-impl.ts
Improve swap interaction and refetch api
=> feat: Improve swap interaction

packages/web/src/components/common/select-price-range-cutom-controller/SelectPriceRangeCutomController.tsx, packages/web/src/constants/option.constant.ts, packages/web/src/hooks/pool/use-select-pool.tsx, packages/web/src/repositories/pool/mock/pool-detai-by-path.json, packages/web/src/utils/swap-utils.spec.ts
Change tick spacing from 2 to 1 for 0.01 percent fee tier pools.
=> feat: Change tick spacing for 0.01 percent fee tier pool

.github/workflows/test.yml
Update github actions scripts.
- Remove `yarn build:module` steps.
=> chore: Update github actions scripts

packages/web/src/common/clients/wallet-client/transaction-messages/pool.ts, packages/web/src/repositories/pool/pool-repository-impl.ts
Change the tokenpath parameter of the createIncentive function to a native path.
=> fix: Change parameter of the CreateIncentive function

packages/web/src/containers/my-liquidity-container/MyLiquidityContainer.tsx, packages/web/src/hooks/common/use-position-data.ts
Fix loading positions in pool detail page.
=> fix: Fix loading positions in pool detail page

packages/web/src/repositories/position/position-repository-impl.ts
- Change reward token type condition.
- Add collect reward message in unstake position.
=> fix: Fix a injection messages

packages/web/src/components/pool/staking-content-card/StakingContentCard.tsx, packages/web/src/components/pool/staking-content/StakingContent.tsx, packages/web/src/components/unstake/select-unstake-result/SelectUnstakeResult.tsx, packages/web/src/constants/option.constant.ts, packages/web/src/containers/staking-container/StakingContainer.tsx, packages/web/src/repositories/position/position-repository-impl.ts, packages/web/src/utils/number-utils.ts
- Apply staking APR in pool detail page.
- Remove collect reward in unstake position message.
=> fix: Fix a Integration API

packages/web/src/hooks/pool/use-pool.tsx, packages/web/src/hooks/pool/use-select-pool.tsx, packages/web/src/react-query/pools/queries.ts, packages/web/src/react-query/pools/types.ts, packages/web/src/repositories/pool/pool-repository-impl.ts, packages/web/src/repositories/pool/pool-repository.ts
This was changed because the data in ApiGetPools for RPC functions is large 
and has a negative impact on chain and interface performance.
=> feat: Improve RPC data calls

packages/web/src/repositories/position/position-repository-impl.ts
Add position approve message in decrease liquidity. (for native token wrapping)
=> feat: Add position approve message in decrease liquidity

packages/web/src/containers/pool-pair-information-container/PoolPairInformationContainer.tsx, packages/web/src/containers/staking-container/StakingContainer.tsx, packages/web/src/hooks/common/use-position-data.ts, packages/web/src/hooks/swap/use-swap-handler.tsx, packages/web/src/pages/earn/pool/[pool-path]/index.tsx, packages/web/src/react-query/positions/queries.ts, packages/web/src/react-query/positions/types.ts
- Fix a swap button conditions.
- Improve loading interaction in pool details.
=> fix: Fix a UI issues

packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx
Fix a current price on pool selection graph.
=> fix: Fix a pool selection graph

packages/web/src/components/common/header-side-menu-modal/HeaderSideMenuModal.styles.ts, packages/web/src/components/common/header-side-menu-modal/HeaderSideMenuModal.tsx, packages/web/src/components/common/header/Header.tsx, packages/web/src/constants/header.constant.ts
If you have a hidden menu, move the submenu to the header .
=> feat: Handle blocked pages

packages/web/src/components/common/my-position-card/MyPositionCard.tsx, packages/web/src/components/wallet/wallet-balance-detail-info/WalletBalanceDetailInfo.tsx, packages/web/src/containers/wallet-balance-container/WalletBalanceContainer.tsx
=> fix: Fix a wallet issue

packages/web/src/resources/chains.json
Add `beta.gnoland` chain configure.
=> chore: Add beta gnoswap chain configure

packages/web/src/containers/trending-card-list-container/TrendingCardListContainer.tsx
=> fix: remove trending token sign

packages/web/src/components/pool/my-position-card/MyPositionCard.styles.ts, packages/web/src/components/pool/my-position-card/MyPositionCard.tsx, packages/web/src/containers/wallet-balance-container/WalletBalanceContainer.tsx, packages/web/src/react-query/positions/queries.ts
Fix wallet loading and user position fetch errors.
=> fix: fix wallet loading and user position fetch errors

packages/web/src/resources/chains.json
Add chain meta information by QA stage.
=> chore: add chain meta information

packages/web/src/containers/token-chart-container/TokenChartContainer.tsx
[GSW-1257](https://onbloc.atlassian.net/browse/GSW-1257)
Fix
---
- show 1M, 1Y, ALL chart with current price
[GSW-1257]: https://onbloc.atlassian.net/browse/GSW-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GSW-1257 fix: chart data

packages/web/src/hooks/swap/use-swap.tsx, packages/web/src/repositories/swap/swap-router-repository-impl.ts
Feature
---
- apply slippage for swap
=> SGW-1165 feat: apply slippage for swap

packages/web/src/components/swap/setting-menu-modal/SettingMenuModal.tsx, packages/web/src/constants/option.constant.ts
Feature
---
- update maximum slippage: `30%` -> `50%`
=> GSW-1165 feat: increase maximum slippage

packages/web/src/hooks/swap/use-swap-handler.tsx
Fix
--- 
- show proper `min.recieved` `max.sent` value
=> fix: show proper slippage value

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/repositories/pool/pool-repository-impl.ts
After creating the position, add a transaction message to set up the NFT.
=> feat: add a transaction message for setting up NFTs after add position

packages/web/src/components/common/select-price-range-cutom-controller/SelectPriceRangeCutomController.tsx
=> fix: apply decimal 6

packages/web/src/components/common/token-info-cell/TokenInfoCell.tsx, packages/web/src/pages/earn/add.tsx
- Token path responsive condition.
- Add multilingualism keys.
=> fix: enhance UI/UX

packages/web/src/hooks/stake/use-stake-data.ts
Adjust pooled token amount in stake.
=> fix: adjust pooled token amount in stake

packages/web/src/containers/token-list-container/TokenListContainer.tsx
Fix
---
- 1d change value of token table in main page
=> GSW-1318 1day change value of token table in main page

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts
Feat
---
- apply slippage to reposition
=> GSW-1165 Slippage for Reposition

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts
Fix
---
- reposition slippage : 5% -> 0.5%
- decrease position slippage : 100% -> 50%
=> Fix default slippage

packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx, packages/web/src/components/common/select-price-range-custom/SelectPriceRangeCustom.tsx, packages/web/src/components/common/select-price-range-custom/SelectPriceRangeCustomPosition.tsx, packages/web/src/components/common/select-price-range-cutom-controller/SelectPriceRangeCutomController.tsx, packages/web/src/components/pool/pool-pair-info-content/PoolPairInfoContent.tsx, packages/web/src/hooks/pool/use-select-pool.tsx
- Adds processing for Min Tick and Max Tick when adding liquidity. 
- Change to calculate the current price from the tick number.
=> fix: handling end ticks in pools

packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx, packages/web/src/components/common/select-price-range-custom/SelectPriceRangeCustom.tsx, packages/web/src/components/common/select-price-range-custom/SelectPriceRangeCustomPosition.tsx, packages/web/src/constants/option.constant.ts, packages/web/src/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/containers/pool-add-liquidity-container/PoolAddLiquidityContainer.tsx
Feat
---
- use only available tick on add/reposition liquidity
=> GSW-1301 Use available tick with tick spacing

packages/web/src/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/pages/earn/add.tsx
Fix
---
- `earn/add` page rerender issue caused by url update
=> GSW-1342 `earn/add` rerender issue

packages/web/src/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/containers/pool-add-liquidity-container/PoolAddLiquidityContainer.tsx
Fix
---
- refix issue for `earn/add`, `earn/pool/add`, `earn/pool/position/reposition`
=> GSW-1342: fix tick param issue

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/hooks/reposition/use-reposition-handle.tsx, packages/web/src/repositories/position/position-repository-impl.ts, packages/web/src/utils/liquidity-utils.ts, packages/web/src/utils/reposition-utils.ts, packages/web/src/utils/swap-utils.ts
Description
---
- fix some liquidity calculation logic
- separate calculation logics
=> GSW-1355 reposition amount logic

packages/web/src/repositories/swap/swap-router-repository-impl.ts
Remove the logic that was converting Wrapped GNOTs to GNOTs on swap and make Wrapped GNOTs swappable.
=> feat: swap by wrapped GNOT

packages/web/src/common/values/token-constant.ts, packages/web/src/containers/asset-list-container/AssetListContainer.tsx, packages/web/src/containers/select-token-container/SelectTokenContainer.tsx, packages/web/src/containers/token-chart-container/TokenChartContainer.tsx, packages/web/src/hooks/swap/use-token-trading-modal.tsx
Descrition
---
- check special token with path
=> Fix compare path instead of symbol

packages/web/src/components/common/missing-logo/MissingLogo.tsx, packages/web/src/components/common/tooltip/Tooltip.tsx, packages/web/src/components/pool/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/components/pool/staking-content/StakingContent.tsx
Description
---
- refactor: tooltip param name
- disable scroll when hover on tooltip
- hide staking guide tooltip when show staking info tooltip
=> GSW-1388 Enhance tooltip

packages/web/src/components/common/notification-list/NotificationItem.tsx, packages/web/src/components/common/tooltip/Tooltip.tsx, packages/web/src/components/home/banner/Banner.tsx, packages/web/src/components/incentivize/disclaimer/Disclaimer.tsx, packages/web/src/components/leaderboard/learn-more/LearnMore.tsx, packages/web/src/components/pool/staking-content/StakingContent.tsx, packages/web/src/components/pool/staking-header/StakingHeader.tsx, packages/web/src/components/unstake/unstake-liquidity/UnstakeLiquidity.tsx, packages/web/src/components/unstake/unstake-position-modal/UnstakePositionModal.tsx, packages/web/src/constants/external-url.contant.ts, packages/web/src/constants/footer.constant.tsx, packages/web/src/constants/header.constant.ts, packages/web/src/containers/gnoswap-brand-container/GnoswapBrandContainer.tsx
Description
---
- Fix: unstaking apr calculation
- Refactor: external link constants
- Tooltip
- optimize callback condition
- disable auto hide scrollbar
=> GSW-1402 Unstaking APR

packages/web/src/components/common/reposition-modal/RepositionModal.tsx, packages/web/src/components/common/select-price-range-custom/SelectPriceRangeCustomReposition.tsx, packages/web/src/components/common/select-price-range-reposition/SelectPriceRangeReposition.tsx, packages/web/src/components/common/select-price-range/SelectPriceRange.tsx, packages/web/src/components/dashboard/activity-list-table/ActivityListTable.tsx, packages/web/src/components/dashboard/activity-list/ActivityList.tsx, packages/web/src/components/reposition/reposition-broadcast-progress/RepositionBroadcastProgress.tsx, packages/web/src/components/reposition/reposition-select-range/RepositionSelectRange.tsx, packages/web/src/constants/skeleton.constant.ts, packages/web/src/containers/dashboard-activities-container/DashboardActivitiesContainer.tsx, packages/web/src/hooks/reposition/use-reposition-handle.tsx
Description
---
- fix reposition preset issue
=> GSW-1405 Reposition issues

packages/web/src/components/remove/remove-position-modal/RemovePositionModal.tsx, packages/web/src/containers/token-chart-container/TokenChartContainer.tsx, packages/web/src/repositories/swap/swap-router-repository-impl.ts, packages/web/src/utils/new-number-utils.ts
Description
---
- fix y-axis legned gap
- fix number formatting exception
- hide fee info when fee doesn't exist on remove position page
=> Fix Issues

packages/web/src/components/pool/exchange-rate-graph/ExchangeRateGraph.styles.ts, packages/web/src/components/pool/exchange-rate-graph/ExchangeRateGraph.tsx, packages/web/src/components/stake/quick-pool-info/QuickPoolInfo.styles.ts, packages/web/src/components/stake/quick-pool-info/QuickPoolInfo.tsx, packages/web/src/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/containers/exchange-rate-graph-container/ExchangeRateGraphContainer.tsx, packages/web/src/containers/quick-pool-info-container/QuickPoolInfoContainer.tsx, packages/web/src/layouts/earn-add-layout/EarnAddLayout.styles.ts, packages/web/src/layouts/earn-add-layout/EarnAddLayout.tsx, packages/web/src/layouts/increase-liquidity-layout/IncreaseLiquidityLayout.styles.ts, packages/web/src/layouts/pool-add-layout/PoolAddLayout.styles.ts, packages/web/src/layouts/pool-add-layout/PoolAddLayout.tsx, packages/web/src/layouts/reposition/RepositionLayout.styles.ts, packages/web/src/pages/earn/add.tsx, packages/web/src/pages/earn/pool/add.tsx
Description
---
- display pool information on add page
=> GSW-1356 display pool data on add liquidity

packages/web/src/containers/increase-liquidity-container/IncreaseLiquidityContainer.tsx, packages/web/src/hooks/increase/use-increase-handle.tsx
Fix UI issues on the increase liquidity page.
=> fix: increase liquidity area

packages/web/src/components/common/my-position-card/MyPositionCard.tsx, packages/web/src/components/common/sub-menu-button/SubMenuButton.tsx, packages/web/src/components/common/sub-menu-button/sub-menu/SubMenu.stories.tsx, packages/web/src/components/common/sub-menu-button/sub-menu/SubMenu.styles.ts, packages/web/src/components/common/sub-menu-button/sub-menu/SubMenu.tsx, packages/web/src/components/common/wallet-connector-button/WalletConnectorButton.styles.ts, packages/web/src/components/common/wallet-connector-button/WalletConnectorButton.tsx, packages/web/src/components/pool/my-liquidity-content/MyLiquidityContent.styles.ts, packages/web/src/components/pool/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/components/pool/my-position-card/MyPositionCard.styles.ts
Feature
---
- show sub menu when hover
- pool page tooltip overflow
- wallet connect button size
- earn card value `-` when one of usd is missing
=> GSW-1433 Minor issues

packages/web/src/react-query/positions/use-get-positions-by-address.ts
Remove the default value of an option value in a React query variable.
=> fix: show closed positions

packages/web/src/components/pool/my-position-card/MyPositionCardBalanceContent.tsx, packages/web/src/utils/new-number-utils.ts
Fix
---
- decimal check for balance
=> fix: balance number decimal

packages/web/src/utils/new-number-utils.ts
Description
---
- hotfix nubmer handling undefined issue
=> hotfix: number util undefined issue

packages/web/src/hooks/common/use-position.ts, packages/web/src/repositories/position/position-repository-impl.ts, packages/web/src/repositories/position/position-repository.ts
Description
---
- fix claim all issue
=> GSW-1455 fix claim all bug

packages/web/src/views/pool/pool-decrease-liquidity/hooks/use-decrease-position-modal.tsx, packages/web/src/views/pool/pool-remove/containers/remove-position-modal-container/RemovePositionModalContainer.tsx
Description
---
- fix : handle locale string number
=> GSW-1491 fix remove toggle issue

packages/web/src/components/swap/swap-card/SwapCard.tsx, packages/web/src/hooks/swap/use-swap-handler.tsx
Description
---
- fix swap button status check sequence
=> GSW-1493 Fix Swap button status

packages/web/src/hooks/common/use-interaction-observer.ts, packages/web/src/views/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.styles.ts, packages/web/src/views/pool/pool-detail/components/staking/staking-content/StakingContent.styles.ts, packages/web/src/views/pool/pool-detail/components/staking/staking-content/StakingContent.tsx, packages/web/src/views/pool/pool-detail/containers/staking-container/StakingContainer.tsx
Description
---
- fix staking guide tooltip
=> GSW-1437 Fix tooltip

packages/web/src/views/pool/pool-decrease-liquidity/hooks/use-decrease-position-modal.tsx, packages/web/src/views/pool/pool-increase-liquidity/hooks/use-increase-position-modal.tsx
Description
---
- fix amount display issues
=> GSW-1571 Fix increase decrease amount

packages/web/src/views/governance/components/my-delegation/MyDelegation.tsx
In the My Delegation Information area of Governance, 
resolves an issue where the activation behaviour of the hover tooltip was incorrectly applied.
=> fix: fix activating the My delegation information tooltip

packages/web/src/common/values/index.ts, packages/web/src/common/values/text-constant.ts, packages/web/src/views/pool/pool-add/components/additional-info/quick-pool-info/QuickPoolInfo.tsx, packages/web/src/views/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx
Manage static text as a variable. 
- Add a constant variable to manage static text that doesn't need to be translated.
=> chore: manage static text as a variable

packages/web/src/common/clients/wallet-client/transaction-messages/staker.ts
Change to disable parameters that are incorrect for the beta.
A contract is a version of wrap and unwrap without the added options.
=> fix: change to disable parameters that are incorrect for the beta

packages/web/src/models/launchpad/launchpad-project-model.ts, packages/web/src/repositories/launchpad/mock/launchpad-project-list.json, packages/web/src/repositories/launchpad/mock/launchpad-project.json, packages/web/src/repositories/launchpad/response/launchpad-response.ts
Add missing launchpad project response data.
- Reward Token Info
=> feat: add missing launchpad project response data

packages/web/src/hooks/common/use-debounce.tsx, packages/web/src/views/launchpad/LaunchpadLayout.styles.ts, packages/web/src/views/launchpad/components/launchpad-project-list/LaunchpadProjectList.tsx, packages/web/src/views/launchpad/components/launchpad-project-list/launchpad-project-list-table/LaunchpadProjectListTable.tsx, packages/web/src/views/launchpad/components/launchpad-project-list/launchpad-project-list-table/launchpad-project-info/launchpad-project-info-chip/LaunchpadProjectInfoChip.styles.ts, packages/web/src/views/launchpad/containers/launchpad-project-list-container/LaunchpadProjectListContainer.tsx, packages/web/src/views/launchpad/launchpad-detail/components/common/launchpad-status-time-chip/LaunchpadStatusTimeChip.styled.ts, packages/web/src/views/launchpad/launchpad-detail/components/launchpad-my-participation/launchpad-my-participation-box/LaunchpadMyParticipationBox.tsx
Apply infinite scrolling to Launchpad project list tables
=> Feature [GSW-1724]: Project-list infinite scroll

packages/web/src/views/launchpad/LaunchpadLayout.styles.ts, packages/web/src/views/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/LaunchpadActiveProjectsCardList.styles.ts, packages/web/src/views/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/launchpad-active-project-card/LaunchpadActiveProjectCard.styles.ts, packages/web/src/views/launchpad/components/launchpad-main/LaunchpadMain.tsx, packages/web/src/views/launchpad/components/launchpad-project-list/launchpad-project-list-table/launchpad-project-info/LaunchpadProjectInfo.styles.ts, packages/web/src/views/launchpad/components/launchpad-project-list/launchpad-project-list-table/launchpad-project-info/LaunchpadProjectInfo.tsx, packages/web/src/views/launchpad/containers/launchpad-main-container/LaunchpadMainContainer.tsx
Improved the mobile responsive design of the main page.
=> Fix [GSW-1725]: launchpad responsive main page

packages/web/src/utils/rpc-utils.ts
Fix Price graph not displaying when creating a pool.
Fix the parser because it's having trouble parsing the data.
=> fix: fix Price graph not displaying when creating a pool

packages/web/pages/earn/index.tsx, packages/web/pages/earn/pool/index.tsx, packages/web/src/hooks/common/use-position.ts, packages/web/src/models/pool/pool-staking.ts, packages/web/src/react-query/pools/use-remove-external-incentive.ts, packages/web/src/react-query/query-keys.ts, packages/web/src/repositories/pool/pool-repository.ts, packages/web/src/repositories/pool/pool.message.ts, packages/web/src/repositories/pool/request/remove-external-incentive-request.ts, packages/web/src/repositories/pool/response/pool-staking-response.ts, packages/web/src/repositories/position/position-repository-impl.ts, packages/web/src/repositories/position/position-repository.ts, packages/web/src/repositories/position/position.message.ts, packages/web/src/repositories/position/request/claim-request.ts, packages/web/src/views/earn/Earn.tsx, packages/web/src/views/governance/components/my-delegation/my-delegation-modals/MyDelegationDelegateModal.tsx, packages/web/src/views/pool/pool-detail/PoolDetail.tsx, packages/web/src/views/pool/pool-detail/components/my-liquidity/MyLiquidity.tsx, packages/web/src/views/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.styles.ts, packages/web/src/views/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/views/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx, packages/web/src/views/pool/pool-incentivize/PoolIncentivize.tsx, packages/web/src/views/pool/pool-incentivize/components/incentivize-pool-history/IncentivizePoolHistory.tsx, packages/web/src/views/pool/pool-incentivize/components/incentivize-pool-history/incentivize-pool-history-box/IncentivizePoolHistoryBox.tsx, packages/web/src/views/pool/pool-incentivize/containers/incentivize-pool-history-container/IncentivizePoolHistoryContainer.tsx, packages/web/src/views/privacy/PrivacyLayout.styles.ts, packages/web/src/views/terms/TermsLayout.styles.ts
We need to implement a new function to handle claiming rewards for a single position. This will improve the flexibility of our codebase and allow for more granular control over claiming operations.
Test Tx: [link](https://gnoscan.io/transactions/details?txhash=IggOc%20zF2HVJm3mbhdiSmUCs9mrjwRebYemCvLeMvJ0%3D&type=custom&rpcUrl=https%3A%2F%2Fdev.rpc.gnoswap.io&indexerUrl=https%3A%2F%2Findexer-gnoswap.in.onbloc.xyz)
=> Feature [GSW-1915] sendClaim for Single Position

packages/web/src/views/pool/pool-detail/PoolDetail.tsx, packages/web/src/views/pool/pool-detail/components/my-liquidity/MyLiquidity.tsx, packages/web/src/views/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx
Fixes slow page loading when navigating to the pool details page due to loading all position bins data.
=> fix: Fix bins API lookup error for positions when page panning

packages/web/src/views/pool/pool-detail/components/my-liquidity/MyLiquidity.tsx, packages/web/src/views/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx
Add the missing code as it becomes merged.
=> chore: add missing code from #559

packages/web/src/views/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx
Change filter condition of owner.
=> fix: change filter condition of owner

packages/web/src/components/common/header/search-menu-modal/SearchMenuModal.tsx, packages/web/src/components/common/select-token/SelectToken.tsx, packages/web/src/containers/header-container/HeaderContainer.tsx, packages/web/src/containers/select-token-container/SelectTokenContainer.tsx
To enhance user experience by ensuring the recent token list only displays valid tokens that exist in the current asset list.
Currently, the recent token list may display tokens that no longer exist in the asset list, which can lead to confusion and potential errors. This implementation filters out invalid tokens from the recent token list.
=> Fix [GSW-1953] Recent Token List Filter Implementation

packages/web/src/views/wallet/components/wallet-balance/wallet-balance-detail/WalletBalanceDetail.tsx
To enhance the stability and error handling of reward type processing in the Wallet Balance Detail component by implementing proper type validation and safe object access patterns.
This PR addresses a runtime error occurring in the Wallet Balance Detail component when processing claimed rewards with invalid reward types.
=> Fix [GSW-1964] Claim Reward Type exception handling

packages/web/src/components/common/form-input/FormInput.tsx, packages/web/src/components/common/header/search-menu-modal/SearchMenuModal.tsx, packages/web/src/components/common/search-input/SearchInput.tsx, packages/web/src/components/common/select-token/SelectToken.tsx, packages/web/src/components/common/setting-menu-modal/SettingMenuModal.tsx, packages/web/src/components/common/token-amount-input/TokenAmountInput.tsx, packages/web/src/components/home/home-swap/HomeSwap.tsx, packages/web/src/views/governance/components/my-delegation/my-delegation-modals/MyDelegationDelegateModal.tsx, packages/web/src/views/launchpad/launchpad-detail/components/launchpad-participate/LaunchpadParticipate.tsx, packages/web/src/views/pool/common/components/select-price-range/select-price-range-custom/price-steps/PriceSteps.tsx, packages/web/src/views/pool/common/components/select-price-range/select-price-range-custom/starting-price/StartingPrice.tsx, packages/web/src/views/pool/pool-remove/components/remove-liquidity/remove-liquidity-select-list/RemoveLiquiditySelectList.tsx, packages/web/src/views/pool/pool-remove/components/remove-liquidity/remove-liquidity-select-list/remove-liquidity-select-list-item/RemoveLiquiditySelectListItem.tsx, packages/web/src/views/pool/pool-stake/components/stake-position/select-liquidity/select-liquidity-list/SelectLiquidityList.tsx, packages/web/src/views/pool/pool-stake/components/stake-position/select-liquidity/select-liquidity-list/select-lilquidity-list-item/SelectLiquidityListItem.tsx, packages/web/src/views/pool/pool-unstake/components/unstake-liquidity/select-liquidity/SelectLiquidity.tsx, packages/web/src/views/pool/pool-unstake/components/unstake-liquidity/select-liquidity/select-liquidity-item/SelectLiquidityItem.tsx, packages/web/src/views/swap/components/swap-card/swap-card-content/SwapCardContent.tsx, packages/web/src/views/token-detail/components/token-swap/TokenSwap.tsx, packages/web/src/views/wallet/components/asset-send-modal/AssetSendModal.tsx
Optimize input field behavior by customizing default browser features to enhance user experience and maintain consistent UI/UX.
- Disable autocomplete functionality
- Add autocomplete="off" attribute to prevent browser suggestions
- Remove spellcheck feature
- Set spellcheck="false" to eliminate unnecessary underlines
- Optimize additional browser defaults
- Customize input behavior for better user experience
- Maintain consistent UI across different browsers
=> Feat [GSW-1976] Disable default input behaviors

packages/web/src/components/common/setting-menu-modal/SettingMenuModal.tsx, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.stories.tsx, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.styles.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/swap/data/use-swap.tsx, packages/web/src/layouts/swap/components/swap-card/SwapCard.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-content/SwapCardContent.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-header/SwapCardHeader.styles.ts, packages/web/src/layouts/token-detail/components/token-swap/TokenSwap.tsx, packages/web/src/layouts/token-detail/containers/token-swap-container/TokenSwapContainer.tsx, packages/web/src/react-query/router/use-get-routes.ts, packages/web/src/repositories/swap/response/get-routes-response.ts, packages/web/src/repositories/swap/swap-router-repository-mock.ts, packages/web/src/states/swap.ts
- Improving swap-route fetching policies
- Minimize API calls
- When the SwapRoute data is updated, it is also updated in the ConfirmModal
=> [GSW-2048] Swap issue

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/swap/data/use-swap.tsx, packages/web/src/layouts/swap/components/swap-info-chart/swap-token-info/SwapTokenHeader.styles.ts
- Fixed data not being called when selecting a token after entering a swap quantity.
- Execute Wrap/Unwrap
=> [GSW-2048] Swap Issue 2

packages/web/src/components/common/token-amount-input/TokenAmountInput.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/token/ui/use-token-balance-display.tsx, packages/web/src/layouts/launchpad/launchpad-detail/components/launchpad-participate/LaunchpadParticipate.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-content/SwapCardContent.tsx, packages/web/src/layouts/token-detail/components/token-swap/TokenSwap.tsx, packages/web/src/utils/token-utils.spec.ts, packages/web/src/utils/token-utils.ts
This PR introduces a new custom hook useTokenBalanceDisplay for consistent token balance formatting across the application, along with comprehensive test coverage.
- Display format: 2 decimal places for visual representation
- Input format: 6 decimal places for max button and actual token operations
- Custom Hook Implementation
- Edge case  coverage
=> [GSW-2054] max button amount

packages/web/src/hooks/pool/data/use-pool-add-serach-param.ts, packages/web/src/hooks/pool/data/use-pool.tsx, packages/web/src/hooks/token/data/use-gnot-wugnot.tsx
Fixed token path handling issues in ApiGetPool RPC calls that were causing request failures.
- Corrected token path data structure handling
- Improved path formatting logic before RPC requests
- Fixed path construction for tokenA and tokenB
=> [GSW-2130] RPC `ApiGetPool` FE handling

packages/web/src/common/clients/gno-provider/methods/dry-swap.ts, packages/web/src/common/errors/swap/swap-error.ts, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/repositories/swap/swap-router-repository-impl.ts
Implemented dry swap functionality to prevent significant price deviations during swap transactions. This feature performs a preliminary check before executing actual swaps to ensure the estimated output amount doesn't deviate significantly from expected values.
- Added dry swap deviation check before executing swaps
- Implemented error handling for `DRY_SWAP_DEVIATION_EXCEEDED` cases
- Added user-friendly error messages for deviation errors
- Refactored error handling structure for better maintainability
- Added new error type `DRY_SWAP_DEVIATION_EXCEEDED`
- Implemented error handlers object pattern for scalable error management
- Enhanced error message broadcasting system
- Added type safety for error handling
This implementation helps protect users from unexpected price movements by:
- …
=> [GSW-2077] DrySwapRoute handling

packages/web/src/hooks/pool/data/use-decrease-handle.tsx, packages/web/src/hooks/pool/ui/use-decrease-position-modal.tsx, packages/web/src/layouts/pool/pool-decrease-liquidity/components/decrease-position-modal/DecreasePositionModal.tsx, packages/web/src/layouts/pool/pool-decrease-liquidity/containers/decrease-liquidity-container/DecreaseLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-decrease-liquidity/containers/decrease-position-modal-container/DecreasePositionModalContainer.tsx, packages/web/src/repositories/position/position.message.ts, packages/web/src/repositories/position/request/decrease-liquidity-request.ts
Updated the DecreaseLiquidity function parameters to match contract changes.
- Modified DecreaseLiquidity function signature to include updated parameters
- Adjusted the amount validation logic to match new contract requirements
- Updated types and interfaces to reflect contract changes
=> [GSW-2133] Update `DecreaseLiquidity` param

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/hooks/pool/data/use-decrease-handle.tsx, packages/web/src/hooks/pool/data/use-reposition-handle.tsx, packages/web/src/hooks/pool/ui/use-decrease-position-modal.tsx, packages/web/src/hooks/pool/ui/use-increase-position-modal.tsx, packages/web/src/hooks/pool/ui/use-remove-position-modal.tsx, packages/web/src/layouts/pool/pool-decrease-liquidity/containers/decrease-position-modal-container/DecreasePositionModalContainer.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-liquidity-container/RemoveLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-position-modal-container/RemovePositionModalContainer.tsx, packages/web/src/repositories/position/position.message.ts, packages/web/src/repositories/position/request/remove-liquidity-request.ts
- Fixed percentage reflection accuracy for token amounts during liquidity reduction
- Modified liquidity calculation to accurately convert tick values to actual prices
- Convert tick values to exact prices using the tickToPrice function
- Apply a BigNumber operation based on the converted price
- Applied deadline implementation for:
- Mint
- MintAndStake
- IncreaseLiquidity
- DecreaseLiquidity
- RemoveLiquidity
- ExactInSwapRoute
- ExactOutSwapRoute
=> [GSW-2136] DecreaseLiquidity

packages/web/src/components/common/header/sub-menu-button/SubMenuButton.spec.tsx, packages/web/src/constants/external-url.contant.ts, packages/web/src/layouts/leaderboard-layout/Leaderboard.tsx, packages/web/src/layouts/leaderboard-layout/LeaderboardLayout.styles.ts, packages/web/src/layouts/leaderboard-layout/LeaderboardLayout.tsx, packages/web/src/layouts/leaderboard-layout/components/common/common.styles.ts, packages/web/src/layouts/leaderboard-layout/components/copy-referral-link/CopyReferralLink.tsx, packages/web/src/layouts/leaderboard-layout/components/learn-more/LearnMore.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-banner-container/LeaderboardBannerContainer.styles.ts, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-banner-container/LeaderboardBannerContainer.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-list-header-container/LeaderboardListHeaderContainer.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-table-container/LeaderboardTableContainer.tsx, packages/web/src/layouts/leaderboard-layout/leaderboard-list/LeaderboardList.tsx
This PR completes the UI implementation for the leaderboard page according to the design specifications.
=> [GSW-2143] Leaderboard UI

packages/web/src/utils/common.ts
This PR fixes an issue where underscores in pool paths were incorrectly interpreted after URL encoding/decoding. Specifically, paths containing test_token were being incorrectly processed as test/token, causing API requests to fail.
=> Hotfix: Fix URL encoding issue with underscores in pool paths

packages/web/src/components/common/connect-wallet-modal/ConnectWalletModal.tsx, packages/web/src/components/common/connected-social-wallet-modal/ConnectedSocialWalletModal.tsx, packages/web/src/components/common/header/Header.styles.ts, packages/web/src/components/common/header/search-menu-modal/SearchMenuModal.tsx, packages/web/src/components/common/header/wallet-connector-button/wallet-connector-menu/SocialWalletNotification.tsx, packages/web/src/components/common/header/wallet-connector-button/wallet-connector-menu/WalletConnectorMenu.tsx, packages/web/src/components/common/launchpad-modal/launchpad-deposit-modal/LaunchpadDepositModal.styles.ts, packages/web/src/components/common/launchpad-modal/launchpad-deposit-modal/LaunchpadDepositModal.tsx, packages/web/src/components/common/token-info-cell/TokenInfoCell.tsx, packages/web/src/components/hoc/with-local-modal/withLocalModal.styles.ts, packages/web/src/components/home/mobile-token-info/MobileTokenInfo.styles.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.styles.ts, packages/web/src/components/wallet/asset-receive-modal/AssetReceiveModal.styles.ts, packages/web/src/constants/external-url.contant.ts, packages/web/src/hooks/wallet/data/use-wallet.ts, packages/web/src/layouts/governance/components/my-delegation/my-delegation-modals/MyDelegationModals.styles.ts, packages/web/src/layouts/pool/pool-add/components/pool-add-confirm-modal/PoolAddConfirmModal.styles.ts, packages/web/src/layouts/pool/pool-decrease-liquidity/components/decrease-position-modal/DecreasePositionModal.styles.ts, packages/web/src/layouts/pool/pool-incentivize/components/incentivize-pool-modal/IncentivizePoolModal.styles.ts, packages/web/src/layouts/pool/pool-increase-liquidity/components/increase-position-modal/IncreasePositionModal.styles.ts, packages/web/src/layouts/pool/pool-remove/components/remove-position-modal/RemovePositionModal.styles.ts, packages/web/src/layouts/pool/pool-reposition/components/reposition-modal/RepositionModal.styles.ts, packages/web/src/layouts/pool/pool-stake/components/stake-position-modal/StakePositionModal.styles.ts, packages/web/src/layouts/pool/pool-unstake/components/unstake-position-modal/UnstakePositionModal.styles.ts, packages/web/src/layouts/wallet/components/asset-send-modal/AssetSendModal.styles.ts, packages/web/src/utils/token-utils.ts
- This PR fixes a legacy issue that existed on the main page.
=> [GSW-2150] Legacy issue Main

packages/web/src/layouts/governance/components/proposals-list/create-proposal-modal/CreateProposalModal.tsx, packages/web/src/layouts/governance/containers/proposal-list-container/ProposalListContainer.tsx
- Governance package function list data structure change response
- Remove duplicate packages
=> [GSW-2160] `Hotfix` GovernanceSummaryInfo

packages/web/src/layouts/leaderboard-layout/components/common/common.styles.ts, packages/web/src/layouts/leaderboard-layout/components/leaderboard-subheader/LeaderboardSubheader.styles.ts, packages/web/src/layouts/leaderboard-layout/components/next-update/NextUpdate.tsx
Fixing Leaderboard Legacy Issues
- Next update ~ Change text color
- Align bottom of Copy button area
=> GSW-2159 Leaderboard UI

packages/web/src/layouts/dashboard/components/activity-list/activity-list-table/activity-info/ActivityInfo.tsx, packages/web/src/repositories/activity/responses/activity-responses.ts
- handled cases where the OnchainToken data was null
- Implemented proper handling for scenarios when token is null
- Added validation checks before processing token data
- Updated error handling to gracefully manage null token responses
- Ensured backward compatibility with existing token processing logic
=> [GSW-2165] `hotfix` Handling Onchain Token Null

packages/web/src/components/common/double-logo/DoubleLogo.styles.ts, packages/web/src/components/common/select-token/SelectToken.styles.ts, packages/web/src/components/swap/swap-card-content-detail/swap-card-auto-router/SwapCardAutoRouter.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/swap/data/use-swap.tsx, packages/web/src/layouts/swap/components/swap-info-transaction-list/swap-info-transaction-list-table/SwapInfoTransactionListTable.styles.ts, packages/web/src/layouts/swap/components/swap-info-transaction-list/swap-info-transaction-list-table/__mock__/mock-swap-info-transaction.ts, packages/web/src/layouts/swap/containers/swap-container/SwapContainer.tsx, packages/web/src/layouts/token-detail/containers/token-swap-container/TokenSwapContainer.tsx, packages/web/src/repositories/swap/response/swap-history-response.ts
- Fixing Swap page legacy issues
- Specific quantity remains when entering a quantity
- Select a token modal top fixed
- Fixed trade history subarea
- Remove Fee Tier decimal point trailing zeros
- Previous values are still visible when changing swap quantity input
=> [GSW-2157] Legacy Issue Swap

packages/web/src/components/common/connect-wallet-modal/ConnectWalletModal.styles.ts, packages/web/src/components/common/connect-wallet-modal/connect-wallet-modal-divider/ConnectWalletModalDivider.styles.ts, packages/web/src/components/common/launchpad-modal/launchpad-claim-all-modal/LaunchpadClaimAllModal.styles.ts, packages/web/src/components/common/launchpad-modal/launchpad-deposit-modal/LaunchpadDepositModal.styles.ts, packages/web/src/components/wallet/asset-receive-modal/AssetReceiveModal.styles.ts, packages/web/src/layouts/governance/components/my-delegation/my-delegation-modals/MyDelegationModals.styles.ts, packages/web/src/layouts/launchpad/launchpad-detail/components/launchpad-pool-list/launchpad-pool-list-card/LaunchpadPoolListCard.styles.ts
Improved color consistency across modals by updating text color values according to design requirements. This change synchronizes title and fixed text colors between dark and light modes.
- Updated title text colors:
-  Dark mode: Changed to gray300 (#90A2C0)
-  Light mode: Changed to gray400 (#596782)
- Updated fixed text colors:
-  Dark mode: Changed to gray400 (#596782)
-  Light mode: Changed to gray300 (#90A2C0)
- These changes align with the design specifications provided in the Figma document
- Modified theme variables to ensure consistent color application across components
=> [GSW-2164] Color sync

packages/web/src/repositories/activity/responses/activity-responses.ts, packages/web/src/repositories/notification/notification-repository-impl.ts
Integrate the `/users/activity` endpoint API
- Update to the latest API response data interface
- Handles for failed transactions
=> [GSW-2174] UserActivity Response, Fail TX

packages/web/src/containers/recently-added-card-list-container/RecentlyAddedCardListContainer.tsx, packages/web/src/hooks/common/use-loading.tsx, packages/web/src/repositories/token/mock/token-chain.json, packages/web/src/repositories/token/response/token-chain-response.ts
Frontend integration needed to match updated interface
- Before
```
export interface IChainStat {
allTimeVolumeUsd: string;
tvlUsd: string;
volume24hUsd: string;
}
```
- After
```
export interface IChainStat {
tvlUsd: string;
volume24hUsd: string;
swapVolume24hUsd: string;
swapFees24hUsd: string;
}
```
=> [GSW-2175] `v1/chain` data integration

packages/web/src/containers/recently-added-card-list-container/RecentlyAddedCardListContainer.tsx, packages/web/src/layouts/swap/components/swap-info-transaction-list/swap-info-transaction-list-table/SwapInfoTransactionListTable.tsx
Applied the TokenLogo common component to the swap history area.
=> SwapHistory TokenLogo Image

packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx, packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx, packages/web/src/components/common/token-warning-modal/TokenWarningModal.styles.ts, packages/web/src/components/common/token-warning-modal/TokenWarningModal.tsx, packages/web/src/components/home/recently-added-card-list/RecentlyAddedCardList.tsx, packages/web/src/hooks/pool/data/use-increase-handle.tsx, packages/web/src/layouts/pool/common/components/select-price-range/select-price-range-custom/starting-price/StartingPrice.tsx, packages/web/src/layouts/pool/pool-add/components/pool-add-liquidity/PoolAddLiquidity.tsx, packages/web/src/layouts/pool/pool-add/containers/pool-add-liquidity-container/PoolAddLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-detail/PoolLayout.styles.ts, packages/web/src/layouts/pool/pool-detail/PoolLayout.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/MyLiquidity.styles.ts, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.styles.ts, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-header/MyLiquidityHeader.styles.ts, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-header/MyLiquidityHeader.tsx, packages/web/src/layouts/pool/pool-incentivize/components/pool-incentivize/pool-incentivize-details/PoolIncentivizeDetails.styles.ts, packages/web/src/react-query/pools/use-initialize-bins.ts
- Fixing Earn page legacy issues
- Token Warning Modal - Remove Cancel area from modal (uniformity)
- Staking Container button section gap
- Earn liquidity bar removed issue
- Starting Price cache left behind
- Starting Price reference point moving
- Staking related information is frozen and does not change
- Liquidity bar hover not showing hover effect on the bar (see Earn)
=> [GSW-2153] Legacy Issue Earn

packages/web/src/components/common/my-position-card-list/my-position-card/MyPositionCard.tsx, packages/web/src/components/common/reward-tooltip-content/RewardTooltipContent.tsx, packages/web/src/constants/option.constant.ts, packages/web/src/hooks/pool/data/use-decrease-handle.tsx, packages/web/src/hooks/pool/data/use-increase-handle.tsx, packages/web/src/hooks/pool/data/use-position.ts, packages/web/src/hooks/pool/data/use-positions-rewards.ts, packages/web/src/hooks/pool/data/use-reposition-handle.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/stat-tooltip-contents/DailyEarningTooltipContent.tsx, packages/web/src/layouts/pool/pool-detail/components/staking/staking-content/staking-content-card/StakingContentCard.tsx, packages/web/src/layouts/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-remove/components/remove-position-modal/RemovePositionModal.tsx, packages/web/src/layouts/pool/pool-unstake/components/unstake-position-modal/UnstakePositionModal.tsx, packages/web/src/layouts/wallet/components/wallet-balance/wallet-balance-detail/WalletBalanceDetail.tsx, packages/web/src/layouts/wallet/containers/wallet-balance-container/WalletBalanceContainer.tsx, packages/web/src/models/position/mapper/position-mapper.ts, packages/web/src/models/position/position-model.ts, packages/web/src/repositories/position/position.message.ts, packages/web/src/repositories/position/response/position-list-response.ts
Changing the PositionModel interface, Respond to data uses
=> fix: [GSW-2176] Update PositionModel

packages/web/src/repositories/position/position.message.ts
Changed the name of the contract execution function
=> hotfix: UnStakeToken FunctionName

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/containers/token-list-container/TokenListContainer.tsx, packages/web/src/layouts/dashboard/containers/dashboard-activities-container/DashboardActivitiesContainer.tsx, packages/web/src/repositories/notification/notification-repository-impl.ts
Notifications, Activities data handling, and minor issue fixes.
- /activity
- user/activity
- Remove unnecessary CollectFee arguments
=> Fix notification

packages/web/src/containers/token-list-container/TokenListContainer.tsx, packages/web/src/layouts/swap/components/swap-info-chart/swap-token-info/SwapTokenHeader.tsx
A PR that handles known issues.
- Handling when latestPrice data is not available
- SwapChart decimals not applied
=> Fix: TokenPrice Chart decimal

packages/web/src/layouts/token-detail/components/token-chart/token-chart-graph/TokenChartGraph.tsx
This PR fixes an issue where the token detail chart was not displaying correctly due to unsorted data points.
-  The chart data in the TokenChartGraph component was being rendered in a random order, causing the graph to appear jagged and incorrect.
- Added data sorting functionality to TokenChartGraph component
- Sorted data points by timestamp in ascending order 
- Applied .reverse() to display the most recent data first, matching the behavior in SwapTokenChart
- Used getLocalizeTime for consistent time formatting
=> [GSW-2219] `hotfix` TokenChart UI

packages/web/src/common/utils/date-util.ts
This PR fixes an issue with the `getDateUtcToLocal` function to properly handle cases where End Date is not available
- Modified the function to return "-" placeholder instead of "Invalid Date"
- Improved user experience by providing clearer information
- Fixed display issue for Internal Reward (Emission) pools
=> [GSW-2224] Improve getDateUtcToLocal function 

packages/web/src/components/common/header/wallet-connector-button/wallet-connector-menu/wallet-referral-info/WalletReferralInfo.tsx, packages/web/src/hooks/common/use-referral.tsx
This PR improves the wallet referral system by
- Adding the `formatAddress` utility for consistent address formatting across the application
- Creating a new `referrerAddressInfo` object that provides both full and shortened address formats
- Optimizing the priority handling between URL parameters and session storage
- Adding `apiReferrerAddress` to the returned object for better referral source tracking
=> [GSW-2204] Enhance Wallet Referral Address Formatting and Management

packages/web/src/layouts/leaderboard-layout/components/copy-referral-link/CopyReferralLink.tsx, packages/web/src/layouts/leaderboard-layout/components/leaderboard-subheader/LeaderboardSubheader.tsx, packages/web/src/layouts/leaderboard-layout/components/leaderboard-table-row/LeaderboardTableRow.styles.ts, packages/web/src/layouts/leaderboard-layout/components/leaderboard-table-row/LeaderboardTableRow.tsx, packages/web/src/layouts/leaderboard-layout/components/point-composition/PointComposition.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-subheader-container/LeaderboardSubheaderContainer.tsx, packages/web/src/utils/string-utils.ts
This PR refactors the LeaderboardTableRow component to optimize how display values are calculated and rendered
- Consolidated three separate useMemo hooks (displaySwapVolume, displayPositionValue, displayStakingValue) into a single displayValues object
- Modified the formatUsdValue function to include the dollar sign ($) formatting
- Removed redundant calculations that were previously duplicated across multiple hooks
- Improved code readability by using the calculated values directly in the render method
=> [GSW-2199] leaderboard QA

packages/web/src/layouts/earn/components/pool-list/types.ts, packages/web/src/layouts/earn/containers/pool-list-container/PoolListContainer.tsx
This PR improves the sorting functionality in the PoolListContainer component by properly handling empty values.
- Modified the sort function to place items with "-" values at the end of the list when sorting in descending order
- Applied this behavior to TVL, Volume, Fees, and APR columns
- Added documentation comments to improve code readability and maintainability
- Implemented proper value transformation for sorting to handle edge cases
=> [GSW-2229] Fix sorting behavior for empty values in pool list

packages/web/src/components/common/header/Header.tsx, packages/web/src/components/common/header/sub-menu-button/sub-menu/SubMenu.tsx, packages/web/src/components/common/pagination/Pagination.tsx, packages/web/src/constants/page.constant.ts, packages/web/src/layouts/leaderboard-layout/components/leaderboard-table-header/LeaderboardTableHeader.tsx, packages/web/src/layouts/leaderboard-layout/components/leaderboard-table-row/LeaderboardTableRow.tsx, packages/web/src/layouts/leaderboard-layout/components/leaderboard-table/LeaderboardTable.tsx, packages/web/src/layouts/leaderboard-layout/components/next-update/NextUpdate.tsx, packages/web/src/layouts/leaderboard-layout/components/point-composition/PointComposition.tsx, packages/web/src/layouts/leaderboard-layout/components/user-column/UserColumn.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-list-header-container/LeaderboardListHeaderContainer.tsx, packages/web/src/layouts/leaderboard-layout/containers/leaderboard-table-container/LeaderboardTableContainer.tsx, packages/web/src/layouts/leaderboard-layout/leaderboard-list/LeaderboardList.tsx, packages/web/src/react-query/leaderboard/use-get-leaderboard.ts, packages/web/src/utils/string-utils.ts
This PR improved the UX of the Leaderboards page and the referral signup process.
- Pagination
- Decimal
- URL parameter Referral
- Rank UI
=> [GSW-2199] Change Leaderboard & Referral UX 

packages/web/src/components/common/missing-logo/MissingLogo.tsx, packages/web/src/components/common/overlap-token-logo/OverlapTokenLogo.tsx, packages/web/src/constants/option.constant.ts, packages/web/src/layouts/earn/components/incentivized-pool-card-list/incentivized-pool-card/IncentivizedPoolCard.tsx, packages/web/src/layouts/earn/components/pool-list/pool-list-table/pool-info/PoolInfo.tsx, packages/web/src/layouts/pool/pool-add/components/additional-info/quick-pool-info/QuickPoolInfo.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-header/PoolPairInfoHeader.tsx, packages/web/src/layouts/pool/pool-detail/components/staking/staking-content/StakingContent.tsx, packages/web/src/models/pool/info/pool-list-info.ts
This PR changes the content of the RewardToken tooltip
- ${token_name} (Internal Reward-Tier1 / External Reward)
- Apply to RewardTokenType
=> [GSW-2234] RewardToken Tooltip

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.tsx
Router Fee column notation changes PR
- Exposing percentage values in the RouterFee column
=> [GSW-2233] Update RouterFee Column

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.tsx, packages/web/src/utils/swap-utils.ts
Separated the logic for calculating RouterFee into a common function.
Separated into common functions to reduce management points
=> [GSW-2233] RouterFee util

packages/web/src/components/common/missing-logo/MissingLogo.styles.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/PoolPairInformation.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-header/PoolPairInfoHeader.tsx, packages/web/src/layouts/pool/pool-detail/containers/pool-pair-information-container/PoolPairInformationContainer.tsx
PR to fix UI issues on mobile on the Earn page
- MissingLogo Component
- PoolPair Component
=> fix: Earn MobileUI

packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx, packages/web/src/utils/new-number-utils.ts
In this PR, we've improved the logic for calculating depositRatio to handle Pool Price dependencies more reliably.
- Improved Pool Price exception handling
- Set default value (DEFAULT_PRICE_FACTOR) in case Pool Price is invalid
Changed to safely utilise Pool Price when calculating token ratio
- Handling exception situations
- Maintain default use logic when both tokens have no balance
=> [GSW-2250] Token ratio calculation

packages/web/src/common/values/data-constant.ts, packages/web/src/components/common/header/wallet-connector-button/wallet-connector-menu/wallet-referral-info/WalletReferralInfo.styles.ts, packages/web/src/components/common/header/wallet-connector-button/wallet-connector-menu/wallet-referral-info/WalletReferralInfo.tsx, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx, packages/web/src/hooks/common/use-referral.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/BalanceTooltipContent.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx, packages/web/src/utils/token-utils.ts
GSW-2204, GSW-2234, GSW-2250 UX improvement work PR.
- GSW-2204
- Remove ref from URL parameter when user registers a referral
- Referred By Tooltip
- GSW-2234
- Sort reward types
- GSW-2250
- Added PoolPrice exception handling for individual positions
- Same rounding and rounding logic as for position
=> [GSW-2204, GSW-2234, GSW-2250] UX Issue

packages/web/src/common/values/token-constant.ts, packages/web/src/layouts/dashboard/components/dashboard-info/dashboard-info-title/DashboardInfoTitle.tsx, packages/web/src/layouts/portfolio/components/asset-send-modal/AssetSendModal.stories.tsx
This PR is a modification to the GNOT token's metadata
- GNOT token logo url
=> hotfix: Update GNOT metadata

packages/web/src/components/common/reward-tooltip-content/RewardTooltipContent.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-liquidity-content/MyLiquidityContent.tsx, packages/web/src/layouts/pool/pool-detail/components/staking/staking-content/incentivized-token-detail-tooltip-content/IncentivizeTokenDetailTooltipContent.tsx, packages/web/src/utils/pool-utils.ts
- This PR is an action that changes the alignment policy of tooltip data.
- IncentivizeToken Tooltip data
- Daily Earning (Token A/B)
- Reward (Token A/B)
=> [GSW-2274] Sorting Tooltip data

packages/web/src/common/values/data-constant.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.stories.tsx, packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-button-tooltip/SwapButtonTooltip.stories.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.stories.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.tsx, packages/web/src/hooks/common/use-network-fee.ts, packages/web/src/hooks/gas/use-get-estimate-gas-info.ts, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/layouts/swap/components/swap-card/SwapCard.stories.tsx, packages/web/src/models/swap/swap-summary-info.ts, packages/web/src/utils/gas-utils.ts
This PR is an operation that provides gasUsed, gasWanted multiplied by a buffer value.
=> [GSW-2058] GasEstimation

packages/web/src/hooks/common/use-background.tsx, packages/web/src/hooks/wallet/data/use-wallet.ts, packages/web/src/providers/social-wallet-provider/SocialWalletProvider.tsx
After developing the Adena Autolock feature, we encountered an unexpected issue in the user interface that we fixed.
- Added appropriate response logic for locked wallet states
- Optimise UI flow for better user experience
=> [GSW-2293] Adena Wallet locked

packages/web/src/components/common/header/wallet-connector-button/RenderWalletIcon.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/wallet/data/use-wallet.ts, packages/web/src/layouts/swap/components/swap-info-transaction-list/swap-info-transaction-list-table/SwapInfoTransactionListTable.tsx, packages/web/src/states/common.ts, packages/web/src/types/wallet.types.ts
- This PR is an overhaul to the features we provide for Social Login accounts.
- Working on enabling transactions with Social Login accounts
- Fixed an issue with repeated Social Login reconnect popups
- Refactored code related to Social Login
=> [GSW-2315] fix social account

packages/web/src/hooks/gas/use-get-estimate-gas-info.ts, packages/web/src/layouts/swap/components/swap-card/SwapCard.tsx, packages/web/src/layouts/token-detail/components/token-swap/TokenSwap.tsx
This PR is an improvement to the gas cost estimation UI.
- Refetching interval: 10s
- Gasfee loading does not affect the UI
=> [GSW-2331] Improve UI for GasEstimate

packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.tsx
This PR fixes an issue where swap information was not visible when wallets were not connected.
=> [GSW-2332] Swap information was not visible when wallet was not connected

packages/web/src/common/values/token-constant.ts, packages/web/src/hooks/common/use-message.ts, packages/web/src/hooks/pool/data/use-reposition-handle.tsx, packages/web/src/layouts/pool/pool-detail/containers/pool-pair-information-container/PoolPairInformationContainer.tsx, packages/web/src/react-query/query-keys.ts, packages/web/src/repositories/position/position.message.ts, packages/web/src/utils/reposition-utils.ts
This PR fixes a reposition issue.
- Show Slippage Error Modal when a Slippage Error Occurs on Swap
- Reflect DisplayTokenAmount
=> [GSW-2328] Reposition

packages/web/src/layouts/earn/components/pool-list/pool-list-table/pool-info/PoolInfo.tsx, packages/web/src/layouts/earn/containers/pool-list-container/PoolListContainer.tsx
This PR fixes UI issues on the Earn page.
- PoolList
- Pagination
- Display TVL
=> [GSW-2325] Earn Page UI issue - 2

packages/web/src/common/clients/wallet-client/transaction-messages/common.ts, packages/web/src/utils/math.utils.ts
Changed the maximum tolerance value used when generating Approve transaction messages from `UINT64_MAX` to `INT64_MAX`
=> [GSW-2337] Change Max to the maximum value of INT64

packages/web/pages/earn/index.tsx, packages/web/pages/explore/index.tsx, packages/web/pages/governance/index.tsx, packages/web/pages/index.tsx, packages/web/pages/launchpad/index.tsx, packages/web/pages/launchpad/project/index.tsx, packages/web/pages/leaderboard/index.tsx, packages/web/pages/portfolio/index.tsx, packages/web/pages/swap/index.tsx, packages/web/src/constants/common.constant.ts, packages/web/src/layouts/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/LaunchpadActiveProjectsCardList.styles.ts, packages/web/src/layouts/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/launchpad-active-project-card/LaunchpadActiveProjectCard.styles.ts, packages/web/src/layouts/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/launchpad-active-project-card/LaunchpadActiveProjectCard.tsx, packages/web/src/layouts/launchpad/components/launchpad-project-list/LaunchpadProjectList.tsx, packages/web/src/layouts/launchpad/components/launchpad-project-list/launchpad-project-list-table/LaunchpadProjectListTable.tsx, packages/web/src/layouts/launchpad/components/launchpad-project-list/types.ts, packages/web/src/layouts/launchpad/containers/launchpad-project-list-container/LaunchpadProjectListContainer.tsx, packages/web/src/layouts/launchpad/launchpad-detail/components/launchpad-participate/LaunchpadParticipate.tsx, packages/web/src/utils/launchpad-sort-utils.spec.ts, packages/web/src/utils/launchpad-sort-utils.ts
This PR fixes UI issues on the Launchpad page.
- Launchpad project list sorting
- Launchpad Active Project card
- Launchpad Participate Deposit Amount input
- Launchpad My Participation section
- Launchpad Metatag(title)
=> [GSW-2339] Launchpad Page UI issue

packages/web/src/hooks/wallet/data/use-wallet.ts
This PR fixes an unnatural behavior in the wallet connecting process.
=> [GSW-2330] Improve AddEstablished handling

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/hooks/pool/data/use-pool.tsx, packages/web/src/repositories/pool/pool-repository-impl.ts
This PR is an action that removes unnecessary messages from the transaction.
- Mint, MintAndStake
- Remove `SetTokenURILast`
=> [GSW-2343] Remove SetTokenURILast Message

packages/web/src/common/utils/data-check-util.spec.ts, packages/web/src/common/utils/data-check-util.ts, packages/web/src/common/utils/date-util.spec.ts, packages/web/src/common/utils/date-util.ts, packages/web/src/common/utils/denom-util.spec.ts, packages/web/src/common/utils/denom-util.ts, packages/web/src/common/utils/error-util.spec.ts, packages/web/src/common/utils/error-util.ts, packages/web/src/layouts/terms/TermsLayout.tsx, packages/web/src/models/account/mapper/account-mapper.ts
This PR significantly improves TypeScript type safety and adds comprehensive JSDoc documentation to the utility functions in `/packages/web/src/common/utils` package. 
```typescript
export const isNotNullOrUndefined = <T>(target: T | null | undefined): target is T => {
return target !== null && target !== undefined;
};
```
**Why this pattern?**
TypeScript's structural type system doesn't automatically narrow types after runtime checks. Type predicates (`target is T`) explicitly tell the compiler that if the function returns `true`, the type should be narrowed within the conditional block. This bridges the gap between runtime behavior and compile-time type checking.
Example:
```typescript
// Without type predicate, TypeScript doesn't narrow the type
if (isNotNullOrUndefined(value)) {
// …
```
=> feat: Enhance TypeScript Type Safety and Documentation in Utils

packages/web/src/components/common/header/search-menu-modal/SearchMenuModal.tsx
This PR is an application of the TokenPRiceGrade UI to the SearchModal.
=> [GSW-2341] TokenPriceGrade for SearchModal

.yarnrc.yml
.yarnrc.yml update
nodeLinker: node-modules
=> chore: amplify `.yarnrc.yml` file test update

packages/web/src/repositories/pool/pool.message.ts, packages/web/src/repositories/swap-router/swap-router.message.ts, packages/web/src/utils/token-utils.spec.ts, packages/web/src/utils/token-utils.ts
This PR improves the logic for determining if a token is native.
=> [GSW-2354] NativeToken

packages/web/src/layouts/governance/components/proposals-list/proposal-card/ProposalCard.tsx, packages/web/src/layouts/governance/components/proposals-list/view-proposal-modal/ViewProposalModal.tsx, packages/web/src/repositories/governance/mock/get-proposal-details-response.json, packages/web/src/repositories/governance/mock/get-proposals-response.json, packages/web/src/repositories/governance/model/proposal-details-info.ts, packages/web/src/repositories/governance/model/proposals-info.ts
This PR reflects the newly added statusTime field in the proposal data.
=> [GSW-2355] Proposal statusTime

packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/utils/swap-utils.spec.ts, packages/web/src/utils/swap-utils.ts
This PR refactors the token data formatting logic in swap operations to improve code maintainability, type safety, and naming consistency.
- `getSwappedTokenData`: Determines the correct token symbols and amounts based on swap direction.
=> [GSW-2368] swapped data formatting

packages/web/pages/earn/index.tsx, packages/web/pages/index.tsx, packages/web/src/components/common/my-position-card-list/MyPositionCardList.tsx, packages/web/src/components/common/my-position-card-list/my-position-card/MyPositionCard.tsx, packages/web/src/components/home/token-info/TokenInfo.tsx, packages/web/src/global.d.ts, packages/web/src/hooks/common/use-prefetch-navigation.tsx, packages/web/src/layouts/earn/components/earn-my-positions/EarnMyPositions.tsx, packages/web/src/layouts/earn/components/earn-my-positions/earn-my-positions-content/EarnMyPositionsContent.tsx, packages/web/src/layouts/earn/components/incentivized-pool-card-list/incentivized-pool-card/IncentivizedPoolCard.tsx, packages/web/src/layouts/earn/components/pool-list/pool-list-table/pool-info/PoolInfo.tsx, packages/web/src/layouts/launchpad/components/launchpad-active-projects/launchpad-active-projects-content/launchpad-active-projects-card-list/launchpad-active-project-card/LaunchpadActiveProjectCard.tsx, packages/web/src/layouts/launchpad/components/launchpad-project-list/launchpad-project-list-table/launchpad-project-info/LaunchpadProjectInfo.tsx, packages/web/src/layouts/portfolio/components/asset-list/asset-list-table/asset-info/AssetInfo.spec.tsx, packages/web/src/layouts/portfolio/components/asset-list/asset-list-table/asset-info/AssetInfo.tsx, packages/web/src/types/navigator.ts, packages/web/tsconfig.json
This PR implements a prefetch navigation system that preloads routes when users hover over position cards, significantly improving navigation performance and user experience.
- **New Hook**: Created `usePrefetchNavigation` hook for reusable route prefetching across components
- **Network-Aware Optimization**: Enhanced prefetching with intelligent network detection to optimize performance across different connection speeds
- **UI Preload**: Added hover-based prefetching to component
- Position Card
- Token Info Row
- Pool Info Card
- Launchpad Project Card
=> [GSW-2370] Implement prefetch navigation
