gnoswap-labs/gnoswap-interface

packages/web/src/components/home/home-swap/HomeSwap.tsx, packages/web/src/containers/home-swap-container/HomeSwapContainer.tsx, packages/web/src/containers/swap-container/SwapContainer.tsx, packages/web/src/hooks/swap/use-swap-handler.tsx, packages/web/src/states/swap.ts
https://gnoswap-interface-git-develop-onbloc.vercel.app/swap?vercelThreadId=CV4xZ
=> fix: initial swap token A amount

packages/web/src/common/clients/wallet-client/transaction-messages/position.ts, packages/web/src/repositories/position/position-repository-impl.ts
- `Burn` function has disappeared from the `Position` contract.
- Change the `Burn` function to use the `DecreaseLiquidity` function.
=> feat: Migrate position burn to decrease liquidity

packages/web/src/common/clients/wallet-client/transaction-messages/staker.ts
When calling Staker's methods, change the argument type to string.
cc) @r3v4s
=> fix: Fix a injection arguments type to string

packages/web/src/common/values/data-constant.ts
When calling the contract, increase the default `gas-wanted` limit.
=> chore: Increase gas wanted 20,000,000 to 100,000,000

packages/web/src/components/earn/pool-info-lazy-chart/PoolInfoLazyChart.styles.ts, packages/web/src/components/earn/pool-info-lazy-chart/PoolInfoLazyChart.tsx, packages/web/src/components/earn/pool-info/PoolInfo.tsx, packages/web/src/constants/table.constant.ts, packages/web/src/containers/pool-list-container/PoolListContainer.tsx, packages/web/src/containers/token-list-container/TokenListContainer.tsx, packages/web/src/models/pool/mapper/pool-mapper.ts, packages/web/src/react-query/pools/queries.ts, packages/web/src/react-query/pools/types.ts
- Enable lazy loading of graphs in the Pool list.
- On the Main page, set the number of items in the token list to 100. 
- On the Earn page, set the number of items in the pool list to ~100~ 50.
=> feat: Lazy loading graphs from a pool list

packages/web/src/components/swap/swap-card-auto-router/SwapCardAutoRouter.tsx
Resolves an issue with the Router API's changed response value not showing the pool's fees.
=> fix: Display a pool fee of router paths

packages/web/src/repositories/swap/swap-router-repository-impl.ts
Resolves an issue with GNOT swap not working. 
When creating the router key to send to the contract, we use the path from the wrapped GNOT.
=> fix: wrap token before generating router key

packages/web/src/containers/trending-card-list-container/TrendingCardListContainer.tsx
Fix
---
- hide `-` on trending card due to DownArrow means minus
=> fix: hide minus on trending card

packages/web/src/hooks/swap/use-swap-handler.tsx
If there is no USD price, the price impact is calculated based on the pool's price at the time of the swap.
It is calculated from the prices of the route pools used in the swap.
=> feat: calculate the price impact of valueless tokens

packages/web/src/components/common/pool-graph/PoolGraph.tsx, packages/web/src/components/common/tooltip/FloatingTooltip.tsx, packages/web/src/hooks/common/use-floating-tooltip.tsx
Improve the performance of tooltips generated when hovering over full graphs.
- Remove unnecessary code that stacks together when generating tooltips.
=> fix: improve graph tooltip performance

packages/web/src/components/common/bar-area-graph/BarAreaGraph.tsx, packages/web/src/components/common/pool-graph/PoolGraph.styles.ts, packages/web/src/components/common/pool-graph/PoolGraph.tsx, packages/web/src/components/common/pool-graph/PoolGraph.types.ts, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.styles.ts, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx, packages/web/src/components/common/pool-graph/pool-graph-tooltip/PoolGraphTooltip.styles.ts, packages/web/src/components/common/pool-graph/pool-graph-tooltip/PoolGraphTooltip.tsx, packages/web/src/views/earn/components/incentivized-pool-card-list/incentivized-pool-card/IncentivizedPoolCard.tsx, packages/web/src/views/earn/components/pool-list/pool-list-table/pool-info/pool-info-lazy-chart/PoolInfoLazyChart.tsx, packages/web/src/views/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/views/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx
Isolate components of the graph and troubleshoot rendering issues.
=> fix: refactor graph tooltip architecture

packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx
Based on #509 , 
modify the rendering conditions for the graph on the add position page.
=> fix: fix rerender chart in add position

packages/web/src/providers/gnoswap-service-provider/GnoswapServiceProvider.tsx
- Change the mocked launchpad repository to an implementation.
- Apply after the Gnoswap backend is ready.
=> feat: change to an implementation from the launchpad repository

packages/web/src/repositories/launchpad/launchpad-repository-impl.ts
When you receive your Launchpad Rewards and Deposit, we guarantee the order in which you receive them.
The Reward must be called first before the Depsoit amount can be calculated with the Reward.
=> feat: reorder the collect functions in Launchpad

packages/web/src/hooks/common/use-transaction-event-store.ts
After UI update, 
the Gnoscan link in the snack bar now links to the transaction detail page instead of the transaction list.
=> fix: change the gnoscan link in the UI update snackbar

packages/web/src/views/governance/components/my-delegation/MyDelegation.tsx
Mapping in the interface to preserve the look of the existing reward tooltip
- The actual contractual token is a wrapped GNOT (`gno.land/r/demo/wugnot`), 
Implementations of existing interfaces and APIs are not converted to GNOT separately and passed in the reward token list. 
- When claiming, whether to receive `GNOT` or `WUGNOT` is only operated by the flag of whether to wrap or unwrap in the contract method, so if the API converts it, it will be arbitrarily changed, so modify the interface according to the current implementation.
=> fix: map a claimable reward token to gnot

packages/web/src/repositories/swap/swap-router.message.ts
Fix the transaction message field so that the WUGNOT to GNOT unwrap feature works properly.
- Modify the FUNC field in a transaction message
- As-is: `func: 'Unwrap'`
- To-be: `func: 'Withdraw'`
=> Fix [GSW-1966] Correct transaction message for wugnot unwrap

packages/web/src/containers/home-swap-container/HomeSwapContainer.tsx
Fixes an issue where an invalid result (NaN) is displayed directly in the UI when calculating the USD value of a token on the HomeSwap page.
- 'NaN' was exposed directly in the UI when calculating the USD value of a token resulted in an invalid result
- Technical error messages that break user experience
- Modify logic to return null if the result of a calculation is invalid (NaN)
=> Fix [GSW-1960] Token Price NaN

packages/web/src/repositories/position/position.message.ts
Improve reward claims to be received as GNOT instead of WUGNOT by default.
- Change parameter in CollectFee injection message to true
- false (WUGNOT) → true (GNOT)
- Fixed reward claims to be received in GNOT form by default when claiming rewards
=> Fix [GSW-1972] reward claim default GNOT token

packages/web/src/views/pool/pool-detail/PoolDetail.tsx
- Resolve inconsistent scroll behavior when accessing position details via URL hash
- Implement reliable scroll functionality for staking and position sections
- Prevent duplicate scroll actions during component rendering
- Consolidated scroll logic into a single useEffect hook for better maintainability
- Implemented jumpFlagRef to prevent duplicate scroll actions during re-renders
- Added proper handling for three main scroll scenarios:
- Staking section navigation (#staking)
- Specific position navigation (#position-id)
- Default liquidity section navigation
- Added smooth scroll behavior for better user experience
- Ensured DOM elements are properly loaded before scroll execution using setTimeout
- Added proper error handling for non-existent elements
=> Feat [GSW-1952] Earn > Pool position ID scroll

packages/web/src/hooks/swap/use-swap.tsx
Resolves runtime errors and unnecessary API calls when swapping the same token (GNOT ↔ WUGNOT) that occurred after the Swap Route API change.
- Added error return exception handling for same token swaps to the server-side Swap Route API
- When attempting to swap tokens with the same wrappedPath, such as GNOT ↔ WUGNOT:
- Unnecessary API calls occurred
- Runtime error due to server error response
- Normal wrap/unwrap functionality not available
=> fix: [GSW-1965] Add same token exception handling for swap route

packages/web/.env.example, packages/web/src/constants/environment.constant.ts, packages/web/src/hooks/common/use-gnoscan-url.tsx
- Update to the Official Chain URL supported by Gnoscan
- Manage the URLs supported by Gnoscan as environment variables.
- `NEXT_PUBLIC_GNOSCAN_OFFICIAL_CHAIN_IDS`
=> Fix [GSW-1974] Update Gnoscan Support offcial URL

packages/web/src/views/launchpad/launchpad-detail/components/launchpad-detail-click-here/LaunchpadDetailClickHere.tsx, packages/web/src/views/pool/pool-detail/components/my-liquidity/my-liquidity-header/MyLiquidityHeader.tsx
- Update the redirection link in the project page's "Get GNS to participate" button to ensure users are directed to the correct GNS token selection page.
- Enhance Earn > Pool buttons layout (Add, Remove)
- Modified the destination URL from `gno.land/r/gnoswap/v2/gns` to `gno.land/r/gnoswap/v1/gns`
- This change ensures that users are redirected to the page where GNS is pre-selected as Token
=> Fix [GSW-1977] Update Launchpad Click Here Path

packages/web/src/views/pool/pool-add/components/one-click-staking-modal/OneClickStakingModal.tsx
To fix the incorrect button disable behavior in One-Click-staking functionality that was sharing the same validation logic with Pool-Add feature.
The button disable logic was incorrectly shared between Pool-Add and One-Click-staking features, causing unintended behavior. This PR addresses the following issues:
- When GNS is selected as either Token A or B
- Button becomes disabled when Creation Fee(100) + user input exceeds user's GNS balance
- This validation was unnecessarily applied to One-Click-staking
=> Fix [GSW-1983] Remove disabled for One-click staking

packages/web/.gitignore, packages/web/src/common/clients/storage-client/web-storage-client.ts, packages/web/src/common/utils/date-util.ts, packages/web/src/components/common/bar-graph/BarGraph.tsx, packages/web/src/components/common/double-logo/DoubleLogo.styles.ts, packages/web/src/components/common/line-graph/LineGraph.tsx, packages/web/src/components/common/missing-logo/MissingLogo.styles.tsx, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.styles.ts, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.styles.ts, packages/web/src/constants/common.constant.ts, packages/web/src/hooks/pool/data/use-pool-add-serach-param.ts, packages/web/src/hooks/pool/data/use-pool.tsx, packages/web/src/hooks/pool/data/use-select-pool.tsx, packages/web/src/hooks/wallet/data/use-wallet.ts, packages/web/src/layouts/earn/containers/earn-my-position-container/EarnMyPositionContainer.tsx, packages/web/src/layouts/earn/containers/incentivized-pool-card-list-container/IncentivizedPoolCardListContainer.tsx, packages/web/src/layouts/pool/common/components/select-price-range/select-price-range-custom/SelectPriceRangeCustom.tsx, packages/web/src/layouts/pool/common/components/select-price-range/select-price-range-custom/SelectPriceRangeCustomReposition.tsx, packages/web/src/layouts/pool/pool-add/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-add/containers/pool-add-liquidity-container/PoolAddLiquidityContainer.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-content/SwapCardContent.styles.ts, packages/web/src/models/account/account-balance-model.ts, packages/web/src/repositories/pool/pool.message.ts, packages/web/src/repositories/token/token-repository-impl.ts, packages/web/src/repositories/token/token-repository-mock.ts, packages/web/src/utils/pool-utils.ts, packages/web/src/utils/sort-utils.spec.ts, packages/web/src/utils/sort-utils.ts
Fixes all code quality issues identified by SonarQube analytics in the current project.
- Fixed code smells and maintainability issues
- Resolved potential bugs identified by static analysis
- Reduced technical debt
- Exceeded nested function depth
- Unused variables/imports
- Highly complex functions
- Code duplication
- Type stability issues
=> [GSW-2032] SonarQube code quality

packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/swap/data/use-swap.tsx, packages/web/src/react-query/router/use-get-routes.ts
-  UI flickering due to timing issues with price impact calculation
- Improved synchronous calculation of price impact on the client
=> [GSW-1982] sync price impact calculation

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/react-query/router/use-get-routes.ts
- Optimised the processing of swap data in FE
- Unnecessarily many retries
- Removes forced latency of 0.3ms for data processing
=> [GSW-1987] optimize swap route

packages/web/src/components/common/missing-logo/MissingLogo.styles.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/hooks/swap/data/use-swap.tsx
- Instant API call whenever a user enters a swap amount
- Multiple unnecessary API calls during the input process
- Increase server load
- Optimising API calls with debounce
- Wait a certain amount of time (500ms) after user input is complete before calling the API
- Eliminate unnecessary intermediate requests
- Reduce server load
=> [GSW-1984] swap route debounce

packages/web/src/layouts/pool/pool-add/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/utils/common.ts
- Fixed an issue where GRC20-GRC20 token pair selection was not working properly
- Enhanced token path comparison logic in changeTokenA and changeTokenB functions
- Improved GNOT/WUGNOT token handling utilities in common.ts
- Added new utility functions for consistent token path handling:
- `isGnotToken`: Check if token is GNOT/WUGNOT
- `getCorrespondingGnotPath`: Get wrapped/unwrapped path
- `isSameToken`: Compare tokens considering GNOT/WUGNOT equivalence
- `ensureWrappedGnot`: Ensure GNOT is represented as WUGNOT
- Updated token comparison logic to use path instead of wrappedPath
- Fixed token initialization issues in pool pair selection
- Verified GRC20-GRC20 pair selection works correctly
- Tested GNOT-GRC20 pair selection
- Confirmed wrapped/unwrapped token handling
=> feat [GSW-2131] fix token selection in earn add

packages/web/src/layouts/pool/pool-add/containers/additional-info-container/AdditionalInfoContainer.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-liquidity-container/RemoveLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-stake/containers/stake-position-container/StakePositionContainer.tsx
• Show only positions available in the selected pool instead of showing all positions
• Apply consistent filtering logic across Add/Remove Position/Unstake/Stake actions
• Prevent transaction failures by limiting position visibility to relevant pool
• Update both modal views and Earn section right panel
=> [GSW-2132] pool specific position display

packages/web/src/react-query/common/use-emit-transaction-events.ts, packages/web/src/repositories/status/response/sync-info-response.ts, packages/web/src/repositories/status/status-repository-impl.ts
Fix continuous sync-info API calls after transaction execution
The sync-info API is currently being called continuously even after transaction updates are completed. This PR implements a mechanism to stop the sync-info polling once the transaction update is confirmed.
sync-info API is continuously called every 1 second after transaction execution
Maintains the 1-second interval polling of sync-info API after transaction execution
Stops sync-info API calls once transaction update is confirmed complete
=> [GSW-2135] sync-info

packages/web/src/hooks/common/use-background.tsx, packages/web/src/hooks/wallet/data/use-wallet.ts, packages/web/src/utils/transaction-utils.ts
- [GSW-2156] Implement handling for Adena Wallet v1.15.0's new auto-lock security feature to prevent transaction failures.
- [GSW-2154] Fixed account not updating when switching to Wallet extension
- Add wallet lock status detection
- Implement pre-transaction lock status check
- Switch Account
[GSW-2156]: https://onbloc.atlassian.net/browse/GSW-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GSW-2154]: https://onbloc.atlassian.net/browse/GSW-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GSW-2156] `Hotfix` implement auto-lock handling for Adena v1.15.0

packages/web/src/containers/token-list-container/TokenListContainer.tsx
Improve the way the token price graph data is mapped to improve data accuracy.
- Improved logic for calculating graphStatus
- Old: used the first element after sorting
- Changed: to use the last element of the array (latest data)
- Added latestGraphPrice variable
- Introduced variable to clearly extract the latest price of graph data
- Use the price of the last element only if there is data in the array
- Improve conditional handling
- Check the length of the tempTokenPrice.last7d array to access if safely
=> [GSW-2161] `hotfix` Token GraphData mapping issue

packages/web/src/hooks/swap/data/use-swap-handler.tsx
This PR fixes a critical bug where token prices returned as string '0' from the API were incorrectly recognized as valid prices.
The existing code used `!!tokenPrices[checkGnotPath(token.path)]?.usd` to validate prices. When the API returns a price as string '0', this evaluates to `true` with the `!!` operator since it's a non-empty string, causing the system to incorrectly treat it as a valid price.
- Add helper function `getValidUSDValue` to properly handle price validation
- Implement type checking and convert string values to numbers
- Explicitly verify that prices are numeric and greater than zero
- Improve code readability and reusability
=> [GSW-2163] `hotfix` fix token price validation for string values

packages/web/src/hooks/common/use-background.tsx, packages/web/src/providers/social-wallet-provider/SocialWalletProvider.tsx
- Web3auth Continuous Calls: When users attempt to log in via Google or X (Twitter) and then cancel the login process, Web3auth continues to be called repeatedly.
- Email Login Failure: Email login attempts are not triggering Web3auth calls at all.
- Fixed the event handling for social login cancellation to prevent recursive Web3auth calls
- Resolved the issue with Email login not triggering Web3auth integration
- Corrected logo display logic to maintain proper authentication method visualization
- Ensured Adena login state is properly preserved when social login is canceled
=> [GSW-2162] social wallet connect issue

packages/web/src/hooks/pool/data/use-pool-add-serach-param.ts, packages/web/src/utils/common.ts
This PR resolves the mismatch issue between FE and BE regarding the PoolPath data. Previously, FE was processing the path as gnot, while BE was handling it as wugnot. This caused inconsistency in the data flow.
- Updated the usePoolAddSearchParams hook to:
- Process tokenAPath and tokenBPath using checkGnotPath.
- Ensure the processed paths are sorted correctly.
=> [GSW-2198] Earn > Add Position data

packages/web/src/hooks/swap/data/use-swap-handler.tsx
The price impact calculation function estimatePriceImpactByRoutes was only designed to work correctly in EXACT_IN mode. When users perform swaps in EXACT_OUT mode with tokens that don't have USD prices (hasUSDPrice === false), the price impact is calculated incorrectly, leading to misleading information.
- Added an isExactOut parameter to the estimatePriceImpactByRoutes function
- Implemented conditional logic based on swap mode:
- For EXACT_OUT: estimatedAmountBN = estimatedAmountBN.plus(BigNumber(route.amountOut.toString())).dividedBy(routePrice)
- For EXACT_IN: estimatedAmountBN = estimatedAmountBN.plus(BigNumber(route.amountIn.toString())).multipliedBy(routePrice)
=> [GSW-2207] PriceImpact for EXACT_OUT

packages/web/src/repositories/pool/pool-repository-impl.ts
This PR fixes the zoom functionality in the liquidity bar graph on the Add Position page. The issue was caused by a mismatch in the API query parameter name. The endpoint was expecting 'binSize' but our code was using 'bins'.
- Updated API query parameter from 'bins' to 'binSize' in the pool bins endpoint
- Ensured proper zoom functionality with varying bin sizes (40, 80, 160, 320, 640)
- Verified that + and - buttons correctly increase and decrease bin size
=> [GSW-2218] `hotfix` Update query param from 'bins' to 'binSize' Liquidity Graph

packages/web/src/components/common/token-amount-input/TokenAmountInput.tsx, packages/web/src/layouts/governance/components/my-delegation/my-delegation-modals/MyDelegationDelegateModal.tsx
This PR modifies the Delegate input field in the Governance section to accept only integer values instead of decimal values (up to 6 decimal places).
- Changed input validation to accept only integer values
- Maintained minimum unit of 1GNS
- Updated Max button functionality to display maximum amount in integer units
- Added appropriate validation and error handling for non-integer inputs
=> [GSW-2222] Delegate input to receive integer units only

packages/web/src/hooks/common/use-referral.tsx, packages/web/src/hooks/governance/data/use-governance-tx.tsx, packages/web/src/hooks/launchpad/data/use-launchpad-handler.ts, packages/web/src/hooks/pool/data/use-pool.tsx, packages/web/src/hooks/pool/data/use-reposition-handle.tsx, packages/web/src/hooks/swap/data/use-swap.tsx, packages/web/src/layouts/pool/pool-add/containers/earn-add-liquidity-container/EarnAddLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-stake/containers/stake-position-modal-container/StakePositionModalContainer.tsx
This PR resolves an issue where the latest referralAddress value was not being properly reflected in various functions due to a closure issue. The functions were capturing the initial referralAddress value when they were defined, but were not updating when this value changed.
- Added a referralAddressRef using useRef to the useReferral hook so that we can always keep track of the latest referralAddress value.
- Added an effect to update referralAddressRef.current whenever the referralAddress changes.
- Added a getCurrentReferralAddress method to the return value of the useReferral hook that always returns the latest referral address value.
- This ensures that even if a component captures a function early in its lifecycle, calling that function will always return the latest value.
- We've …
=> [GSW-2204] Referral Address closure issue

packages/web/src/layouts/pool/pool-detail/components/my-liquidity/stat-tooltip-contents/DailyEarningTooltipContent.tsx
This PR fixes translation key issues in the Daily Rewards tooltip content:
- Updated `business:rewardType.internal` to `business:rewardType.internal_reward`
- Updated `business:rewardType.external` to `business:rewardType.external_reward`
- Fixed tooltip display in Pool Details page
=> [GSW-2225] Update RewardTooltip TranslateKey

packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx
This PR standardizes the token ratio formatting in Pool Details page
- Replaced `formatRate(depositRatio * 100, { decimals: 0 })` with `Math.round(depositRatio * 100)`
- Applied the same formatting logic to both tokens in the pool
=> [GSW-2227] unify token ratio formatting in Pool Details

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.styles.ts, packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.spec.tsx, packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.stories.tsx, packages/web/src/components/swap/swap-card-content-detail/SwapCardContentDetail.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-button-tooltip/SwapButtonTooltip.stories.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.spec.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.stories.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/layouts/swap/components/swap-card/SwapCard.stories.tsx, packages/web/src/layouts/swap/components/swap-card/SwapCard.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-content/SwapCardContent.spec.tsx, packages/web/src/layouts/swap/components/swap-card/swap-card-content/SwapCardContent.tsx, packages/web/src/layouts/token-detail/components/token-swap/TokenSwap.tsx, packages/web/src/models/swap/swap-summary-info.ts
This PR replaces string literals ("ATOB" and "BTOA") with a proper enum type SwapRateAction for representing swap rate direction throughout the codebase. This change improves type safety, prevents potential typos, and enhances code maintainability.
- Created a new SwapRateAction enum with values ATOB and BTOA
- Updated state definitions in useSwapHandler hook to use the enum type
- Modified relevant components to use the enum instead of string literals
- Updated type definitions in interfaces and function parameters
- Ensured backward compatibility with existing functionality
=> [GSW-2232] SwapRateAction type

packages/web/src/layouts/swap/components/swap-info-transaction-list/swap-info-transaction-list-table/SwapInfoTransactionListTable.tsx, packages/web/src/layouts/swap/containers/swap-info-transaction-list-container/SwapInfoTransactionListContainer.tsx
The transaction list component was experiencing unnecessary re-renders because the time update interval was always set to 1 second (1000ms) regardless of how old the transaction was. This caused performance issues as all transactions were being updated every second, even older ones that didn't need such frequent updates.
Fixed the time difference calculation to properly determine update intervals based on transaction age:
- Recent transactions (< 1 min): update every second
- Medium-age transactions (1 min - 1 hour): update every minute
- Old transactions (> 1 hour): update every hour
=> [GSW-2230] Fix time update interval issue in transaction list

packages/web/src/components/swap/confirm-swap-modal/ConfirmSwapModal.tsx, packages/web/src/components/swap/swap-card-content-detail/swap-card-fee-info/SwapCardFeeInfo.tsx
This PR fixes features related to Swap.
- GSW-2232
- Fix to display the same format (`$-`) as the exchange rate in the swap window even when there is no dollar equivalent
- Added dollar signs to the exchange rate display to provide a consistent UI
- GSW-2233
- Fixed to always calculate the fee based on the output token (tokenB).
=> [GSW-2232, GSW-2233] Fix Swap Feature

packages/web/src/hooks/swap/data/use-swap-handler.tsx
Modified price impact calculation to remove upper limit while maintaining the lower limit of -100%. Implemented useCallback for performance optimization.
- Modified `formatPriceImpact` function to only apply a lower limit (-100%)
- Removed previous upper limit restriction to allow displaying any positive price impact value
- Maintained decimal formatting to 2 decimal places for consistency
- Implemented `useCallback` for performance optimization to prevent unnecessary re-renders
=> [GSW-2235] Remove upper limit for price impact calculation

packages/web/src/components/common/missing-logo/MissingLogo.styles.tsx, packages/web/src/components/common/missing-logo/MissingLogo.tsx, packages/web/src/layouts/earn/components/incentivized-pool-card-list/incentivized-pool-card/IncentivizedPoolCard.tsx, packages/web/src/layouts/earn/components/pool-list/pool-list-table/pool-info/PoolInfo.tsx, packages/web/src/layouts/pool/pool-add/components/additional-info/quick-pool-info/QuickPoolInfo.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-header/PoolPairInfoHeader.tsx, packages/web/src/layouts/pool/pool-detail/components/staking/staking-content/StakingContent.tsx, packages/web/src/utils/token-utils.ts
This PR implements the tooltip text change for reward tokens as specified in the requirements
- Changed tooltip format from simple {token_name} to ${token_name} (Internal Reward-Tier1 / External Reward)
- Added special case handling for GNS tokens that are provided as both Internal and External rewards
- For special cases, tooltip displays as ${token_name} (Internal Reward, <br> External Reward)
- Updated token grouping logic to properly combine multiple reward types
=> [GSW-2234] Handle multiple reward types in token hover tooltip

packages/web/src/constants/common.constant.ts
This PR fixes the issue with SEO meta titles showing "seo.title.default" during initial page load, which creates a poor user experience and might affect SEO performance.
- Added a new constant `DEFAULT_SEO_TITLE` with value "The One-stop Gnoland DeFi Platform | GnoSwap"
- Replaced all occurrences of `DefaultTitle` with `DEFAULT_SEO_TITLE` in SEO-related functions
- This ensures that a meaningful title is displayed during the initial page load before the dynamic content is ready
=> [GSW-2246] Add default SEO title for better UX during page loading

packages/web/src/hooks/pool/data/use-reposition-handle.tsx, packages/web/src/hooks/pool/ui/use-remove-position-modal.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-liquidity-container/RemoveLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-position-modal-container/RemovePositionModalContainer.tsx, packages/web/src/layouts/portfolio/containers/wallet-balance-container/WalletBalanceContainer.tsx, packages/web/src/repositories/position/position.message.ts, packages/web/src/repositories/position/request/remove-liquidity-request.ts
- This PR fixes an issue with the liquidity removal functionality where all positions were using the same liquidity value. Now each position uses its own specific liquidity value.
- This PR fixes an issue where the claim functionality was attempting to process positions with no rewards, causing errors. Now only active positions (with liquidity > 0 and not closed) are passed to the claim functionality.
- Modified `makeRemoveLiquidityMessagesWithApproves` function to accept a mapping of position IDs to liquidity values
- Updated `RemoveLiquidityRequest` interface to use `positionLiquidities` instead of a single `calculatedLiquidity`
- Fixed a syntax error in the `map` function where the return statement was missing
- Added `claimablePositions` using useMemo to filter positions that have …
=> [GSW-2238, GSW-2239] TX-multi message, ClaimAll

packages/web/src/layouts/pool/common/components/select-price-range/select-price-range-custom/SelectPriceRangeCustom.styles.ts, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/utils/reward-utils.ts
This PR implements a filtering mechanism for position rewards, ensuring that only rewards with claimable amounts greater than zero are included in the position data structure.
- Add `isClaimableReward` utility function to validate if a reward has a positive claimable amount
- Use BigNumber library for more accurate numerical comparisons
- Replace manual filtering logic with the reusable utility function
- Update position objects to contain only rewards that are actually claimable
=> [GSW-2266] Filter position rewards to include only claimable amounts

packages/web/src/components/common/pool-graph/PoolGraph.tsx, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx, packages/web/src/layouts/pool/pool-detail/components/pool-pair-information/pool-pair-info-content/PoolPairInfoContent.tsx
This PR fixes the issue where colors are incorrectly applied outside the user-defined range in the liquidity pool chart. As shown in GSW-2272, colors should only appear within the range set by the user.
- Enhanced validation for maxTickPosition and minTickPosition values
- Added disableBlackBar flag to properly manage bar coloring
- Modified chart rendering logic to only display colors within the user-defined range
=> [GSW-2272] PositionGraph black-bar logic

packages/web/src/components/common/bar-area-graph/BarAreaGraph.tsx, packages/web/src/components/common/my-position-card-list/my-position-card/MyPositionCard.tsx, packages/web/src/components/common/pool-graph/PoolGraph.tsx, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx
This PR fixes a bug where tick positions with a value of `0` are treated as invalid values, causing visual bugs in graphs
- Replace `!minTickPosition` and `!maxTickPosition` checks with explicit `== null` checks
- Standardize null checks using `!= null` instead of `!== null` for consistency
- Add `disableBlackBars` flag to control black bar visibility in graphs
- Apply the same logic to Earn > My Range graphs for consistent behavior
=> [GSW-2272] properly handle zero values for min/maxTickPosition

packages/web/src/repositories/position/position.message.ts, packages/web/src/utils/transaction-utils.ts
- This PR fixes a bug that causes the sendAmount to be set incorrectly when executing an IncreaseLiquidity transaction.
- Creating the `getSendAmount` Utility Function
- Common to sendAmount logic
=> [GSW-2275] SendAmount

packages/web/src/hooks/common/use-broadcast-handler.ts, packages/web/src/hooks/common/use-referral.tsx, packages/web/src/hooks/governance/data/use-governance-tx.tsx, packages/web/src/hooks/launchpad/data/use-launchpad-handler.ts, packages/web/src/hooks/pool/ui/use-pool-add-liquidity-confirm-modal.tsx, packages/web/src/hooks/swap/data/use-swap-handler.tsx, packages/web/src/layouts/pool/pool-stake/containers/stake-position-modal-container/StakePositionModalContainer.tsx
This PR fixes an issue where the UI might display incorrect referral information after a failed referral change attempt. When a referral change is rejected by the contract (due to the existing 24-hour cooldown), the UI now correctly maintains and displays the original referral address.
- Fixed UI handling of referral change rejection responses
- Ensured frontend consistently displays the correct active referral address
- Added proper error handling for rejected referral change attempts
- Implemented validation to verify referral display consistency
=> [GSW-2204] Implement 24-hour cooldown period for referral changes

packages/web/src/utils/transaction-utils.ts
This PR refactors the `transaction-utils.ts` module to improve transaction execution performance:
1. Move `generateTransactionDataDocument` call inside the SOCIAL_WALLET branch  
- Avoids unnecessary document creation for non-social wallets (Adena)  
2. Simplify error‐handling and remove redundant null/undefined checks  
3. Merge BigNumber fee calculation and document-modification logic  
As a result, Adena-wallet transactions skip the approval-modal flow entirely, reducing CPU and I/O overhead.
=> [GSW-2321] Refactor transaction-utils to generate documents only for social-wallets

packages/web/src/hooks/common/use-invalidate-queries.ts, packages/web/src/hooks/common/use-transaction-event-store.ts, packages/web/src/hooks/pool/ui/use-decrease-position-modal.tsx, packages/web/src/hooks/pool/ui/use-increase-position-modal.tsx, packages/web/src/hooks/pool/ui/use-pool-add-liquidity-confirm-modal.tsx, packages/web/src/layouts/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx, packages/web/src/layouts/pool/pool-remove/containers/remove-position-modal-container/RemovePositionModalContainer.tsx, packages/web/src/layouts/pool/pool-stake/containers/stake-position-modal-container/StakePositionModalContainer.tsx, packages/web/src/layouts/portfolio/containers/wallet-balance-container/WalletBalanceContainer.tsx, packages/web/src/react-query/positions/use-get-positions-by-address.ts, packages/web/src/utils/common.ts
This PR enhances the transaction event handling by introducing an explicit onSuccess callback that runs after the blockchain transaction is confirmed, decoupling it from the initial “emit” phase
- Executes only once the transaction status is SUCCESS, ensuring UI updates and data refetches occur after on-chain confirmation rather than immediately on emit.
- Reliable refetch with React Query invalidation
=> [GSW-2323] Add onSuccess callback for confirmation-driven refetch in Tx events

packages/web/src/components/common/calendar/Calendar.tsx, packages/web/src/components/common/pool-graph/PoolGraph.tsx, packages/web/src/components/common/pool-graph/pool-graph-svg/PoolGraphSVG.tsx, packages/web/src/components/common/pool-selection-graph/PoolSelectionGraph.tsx, packages/web/src/layouts/earn/components/pool-list/pool-list-table/pool-info/PoolInfo.tsx, packages/web/src/layouts/earn/containers/pool-list-container/PoolListContainer.tsx, packages/web/src/layouts/pool/pool-detail/PoolDetail.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/MyLiquidity.tsx, packages/web/src/layouts/pool/pool-detail/components/my-liquidity/my-detailed-position-card/MyDetailedPositionCard.tsx, packages/web/src/layouts/pool/pool-detail/components/staking/staking-content/StakingContent.tsx, packages/web/src/layouts/pool/pool-detail/containers/my-liquidity-container/MyLiquidityContainer.tsx
This PR fixes UI issues on the Earn page.
- Issue where dotted area is hidden when liquidity bars are in negative range 
- "Hover to view details" tooltip following cursor issue needs fixing
- (Mobile) Date selection not working in Earn > Incentive
- Claim button visible and active when accessing other accounts' position pages -> Claim button should only be visible and active when wallet is connected and position Owner matches the connected wallet address
- When small amounts remain in pool causing TVL to display as <$0.01, process as <$0.01 in Earn > Pool table as well (to apply Informational TVL Grade effect)
- Fix incorrect fee name displayed as "Router Fee"
- Add Position > Liquidity chart
- Current price needs to be fixed at center
- When TVL exists but supplementary data like APR, …
=> [GSW-2325] Earn Page UI issue
